name: Post Commit Messages to Discord

on:
  push:
    branches:
      - main  # Change to match your default branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Send commit messages to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          set -e  # Stop execution if any command fails

          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "Error: DISCORD_WEBHOOK_URL is not set."
            exit 1
          fi

          COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | jq -Rsa .)
          COMMIT_AUTHOR="${{ github.actor }}"
          BRANCH_NAME="${{ github.ref_name }}"

          # Fetch last commit diff (limited to 10 lines for readability)
          DIFF=$(git show --stat --color=never --unified=5 --format="" | head -n 10 | jq -Rs .)

          PAYLOAD=$(jq -n \
            --arg branch "$BRANCH_NAME" \
            --arg message "$COMMIT_MESSAGE" \
            --arg author "$COMMIT_AUTHOR" \
            --arg diff "$DIFF" \
            '{
              embeds: [{
                title: "New Commit Pushed",
                description: ("**Branch:** `" + $branch + "`\n\n**Commit Message:**\n```" + $message + "```\n**Author:** " + $author + "\n\n**Changes:**\n```diff\n" + $diff + "\n```"),
                color: 16776960
              }]
            }'
          )

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               "$DISCORD_WEBHOOK_URL"

