name: Post Commit Messages to Discord

on:
  push:
    branches:
      - main  # Change if your default branch is different
      - feature/*

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we fetch the full repo history

      - name: Send commit messages to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          set -e

          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "Error: DISCORD_WEBHOOK_URL is not set."
            exit 1
          fi

          # If you push multiple commits at once, only the last commit’s message will appear in head_commit.message.
          # For a single commit push, this is fine. If you want all commits, read from github.event.commits[*].message.
          COMMIT_MESSAGE=$(jq -Rs . <<< "${{ github.event.head_commit.message }}")
          COMMIT_AUTHOR="${{ github.actor }}"
          BRANCH_NAME="${{ github.ref_name }}"

          # Show the stat/diff of the most recent commit (limited to 10 lines for brevity)
          DIFF=$(git show --stat --color=never --unified=5 --format="" HEAD | head -n 5 | jq -Rs .)

          PAYLOAD=$(jq -n \
            --arg branch "$BRANCH_NAME" \
            --arg message "$COMMIT_MESSAGE" \
            --arg author "$COMMIT_AUTHOR" \
            --arg diff "$DIFF" \
            '{
              embeds: [{
                title: "New Commit Pushed",
                description: (
                  "**Branch:** `" + $branch + "`\n\n" +
                  "**Commit Message:**\n```" + $message + "```\n" +
                  "**Author:** " + $author + "\n\n" +
                  "**Changes:**\n```diff\n" + $diff + "\n```"
                ),
                color: 16776960
              }]
            }'
          )

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               "$DISCORD_WEBHOOK_URL"
