name: Post Commit Messages to Discord

on:
  push:
    branches:
      - main  # Change to match your default branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Commit Diff
        run: |
          set -e  # Stop execution if any command fails

          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "Error: DISCORD_WEBHOOK_URL is not set."
            exit 1
          fi

          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          COMMIT_AUTHOR="${{ github.actor }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          BRANCH_NAME="${{ github.ref_name }}"

          # Fetch last commit diff (limited to 10 lines for readability)
          DIFF=$(git show --stat --color=never --unified=5 --format="" | head -n 10)

          # Escape newlines for JSON formatting
          DIFF_ESCAPED=$(echo "$DIFF" | sed ':a;N;$!ba;s/\n/\\n/g')

          PAYLOAD=$(cat <<EOF
          {
            "embeds": [{
              "title": "New Commit Pushed",
              "description": "**Branch:** \`$BRANCH_NAME\`\\n\\n**Commit Message:**\\n\`\`\`$COMMIT_MESSAGE\`\`\`\\n**Author:** $COMMIT_AUTHOR\\n\\n**Changes:**\\n\`\`\`diff\\n$DIFF_ESCAPED\\n\`\`\`",
              "color": 16776960
            }]
          }
          EOF
          )

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               "$DISCORD_WEBHOOK_URL"

