name: Post Commit Messages to Discord

on:
  push:
    branches:
      - main  # Change to match your default branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Webhook Secret
        run: |
          echo "Checking if secret is set..."
          echo "DISCORD_WEBHOOK_URL length: ${#DISCORD_WEBHOOK_URL}"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send commit messages to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          set -e  # Stop execution if any command fails

          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "Error: DISCORD_WEBHOOK_URL is not set."
            exit 1
          fi

          curl -X POST -H "Content-Type: application/json" \
               -d '{"content": "New commit pushed: '${{ github.event.head_commit.message }}' by '${{ github.actor }}'"}' \
               "$DISCORD_WEBHOOK_URL"

